### ISSUE TITLE
Crash upon cooling mold.

### ISSUE THREAD

**Issue by Titanium-Aura** [ZLT9/create-modular-tools-fabric#1]
A crash occurs when a mold with molten metal (as an entity) is bulk washed.

Details:
The crash **only** happens if the item is washed when it is thrown, it doesn't not occur when it is in a depot or a belt.
This was tested with only Fabric API, Create Fabric, and Create Modular Tools installed.
I tested two cases, one with a pickaxe mold with molten iron, and one with an axe mold with a stone handle and molten iron. Both resulted in a crash.
The tests were conducted in a new, superflat world.

**Comment by ZLT9** [comment]
Fixed in [version 0.1.1](https://modrinth.com/mod/create-modular-tools/version/0.1.1+mc1.20.1). Thanks for reporting!
