### ISSUE TITLE
我为你的模组制作了汉化资源包。我可以将资源包发送给你，我允许将它加入到模组的更新内容。同时，是否可以允许我在中国的哔哩哔哩网站上发布

### ISSUE THREAD

**Issue by InfGithub** [ZLT9/create-modular-tools-fabric#2]
我为你的模组制作了汉化资源包。我可以将资源包发送给你，我允许将它加入到模组的更新内容。同时，是否可以允许我在中国的哔哩哔哩网站上发布介绍你的模组的相关内容？当经过你的许可后，视频也许在9月底发布，也许是10月初，或许是更晚。
I made a Chinese resource pack for your mod. I can send you the resource pack, and I can allow it to be added to the mod's updates. In the meantime, is it possible for me to post content about your mods on the Bilibili website in China? With your permission, the video may be released at the end of September, or early October, or later.

Email:Yao_icft@outlook.com
If you have any ideas, please contact me.

**Comment by ZLT9** [comment]
Hi! I really appreciate your contribution. I'd love to check your resource pack out, and you're more than welcome to post any content you want about any of my mods. We can definitely discuss adding your resource pack in future updates too. I'll go ahead and close this issue for now. Thanks again for your support!

**Comment by InfGithub** [comment]
Thank you for your support, but I need to deal with my studies and will only have time at 7pm in China. I'll discuss or study with you then.

________________________________
发件人: ZLT ***@***.***>
发送时间: 2024年9月26日 1:40
收件人: ZLT9/create-modular-tools-fabric ***@***.***>
抄送: InfGithub ***@***.***>; Author ***@***.***>
主题: Re: [ZLT9/create-modular-tools-fabric] 我为你的模组制作了汉化资源包。我可以将资源包发送给你，我允许将它加入到模组的更新内容。同时，是否可以允许我在中国的哔哩哔哩网站上发布 (Issue #2)


Hi! I really appreciate your contribution. I'd love to check your resource pack out, and you're more than welcome to post any content you want about any of my mods. We can definitely discuss adding your resource pack in future updates too. Thanks again for your support!

―
