### ISSUE TITLE
Not an issue, someone has stolen your mod

### ISSUE THREAD

**Issue by JpnRndr01** [ZLT9/create-modular-tools-fabric#5]
This guy has straight up reuploaded it...
https://modrinth.com/mod/create-multitools

**Comment by ZLT9** [comment]
Hi, thank you for letting me know about this. I've already reported it on Modrinth. I really appreciate your help!

**Comment by ZLT9** [comment]
Hi, just wanted to let you know that Modrinth has taken down the mod. Thanks again for letting me know!

**Comment by JpnRndr01** [comment]
All good :) the guy who did it seemed like a right asshole
